### PR TITLE
Let user choose which EK3_SRC params to change

### LINKED ISSUE #35: Fusing UGPS and DVL is difficult (extension overwrites EK3_SRC1_POSXY and EK3_SRC1_VELXY)
I've been working on fusing data from the WL UGPS and WL DVL and I'm getting good results in simulation. However, I see that the DVL extension is setting EK3_SRC1_POSXY and EK3_SRC1_VELXY to 6 (ExternalNav) every time it starts up, which complicates field testing.

In my simulations, these settings produce nice fusion:
~~~
1	1	EK3_SRC1_POSXY	3	2	# GPS
1	1	EK3_SRC1_POSZ	1	2	# Baro
1	1	EK3_SRC1_VELXY	3	2	# GPS
1	1	EK3_SRC1_VELZ	0	2	# None
1	1	EK3_SRC1_YAW	1	2	# Compass
1	1	EK3_SRC2_POSXY	0	2	# None
1	1	EK3_SRC2_POSZ	0	2	# None
1	1	EK3_SRC2_VELXY	6	2	# ExternalNav
1	1	EK3_SRC2_VELZ	0	2	# None
1	1	EK3_SRC2_YAW	0	2	# None
1	1	EK3_SRC3_POSXY	0	2	# None
1	1	EK3_SRC3_POSZ	0	2	# None
1	1	EK3_SRC3_VELXY	0	2	# None
1	1	EK3_SRC3_VELZ	0	2	# None
1	1	EK3_SRC3_YAW	0	2	# None
1	1	EK3_SRC_OPTIONS	1	4	# FuseAllVelocities
~~~
These settings use the UGPS for POSXY, and then use both UGPS and DVL for VELXY, as the FuseAllVelocities bit is set.

The workaround is to start the extension, then go into QGC and undo the changes.

Another workaround is to flip SRC1 and SRC2, and use a Python script (or some other method) to send a `MAV_CMD_SET_EKF_SOURCE_SET` message to ArduSub after it boots up to make SRC2 the primary source set:
~~~
1	1	EK3_SRC1_POSXY	6	2	# ExternalNav
1	1	EK3_SRC1_POSZ	1	2	# Baro
1	1	EK3_SRC1_VELXY	6	2	# ExternalNav
1	1	EK3_SRC1_VELZ	0	2	# None
1	1	EK3_SRC1_YAW	1	2	# Compass
1	1	EK3_SRC2_POSXY	3	2	# GPS
1	1	EK3_SRC2_POSZ	1	2	# Baro
1	1	EK3_SRC2_VELXY	3	2	# GPS
1	1	EK3_SRC2_VELZ	0	2	# None
1	1	EK3_SRC2_YAW	1	2	# Compass
1	1	EK3_SRC3_POSXY	0	2	# None
1	1	EK3_SRC3_POSZ	0	2	# None
1	1	EK3_SRC3_VELXY	0	2	# None
1	1	EK3_SRC3_VELZ	0	2	# None
1	1	EK3_SRC3_YAW	0	2	# None
1	1	EK3_SRC_OPTIONS	1	4	# FuseAllVelocities
~~~

Both of these workarounds are complicated.

The current behavior provides a nice out-of-the-box experience for first-time DVL users, but perhaps there's some way to make this optional?

### PR DESCRIPTION
**Pull request by clydemcqueen**
Do not set EK3_SRC parameters by default, but provide buttons instead.

2 use cases are supported:
* use the DVL for horizontal position and velocity
* use the GPS for horizontal position, and the DVL for horizontal velocity

Fixes #35

### CODE REVIEW

**Comment by clydemcqueen** [comment]
Updated to pass the pylint CI (I hope).

I don't know why the deploy CI is failing. I marked the PR 'ready for review' to see if that helps.

**Comment by Williangalvani** [comment]
Oh, the deploy CI is apparently wrong, it should not try to run on PRs.

@clydemcqueen don't we need EK3_SRC_OPTIONS for fusing? I see it set to "4" on your issue but that doesn't seem valid

**Comment by clydemcqueen** [comment]
> don't we need EK3_SRC_OPTIONS for fusing? I see it set to "4" on your issue but that doesn't seem valid

"4" is type; the value is 1. (That's how QGC dumps parameters.)

In my earlier example I had this:
* SRC1_POSXY GPS
* SRC1_VELXY GPS
* SRC2_VELXY DVL
* SRC_OPTIONS 1

I did more simulations after that, and this worked just as well:
* SRC1_POSXY GPS
* SRC1_VELXY DVL
* SRC_OPTIONS is not used

I've been using this simpler setup in the very limited IRL tests we've done so far, and it works just fine. Perhaps more extensive tests will prove that one method works better than the other? Of a careful tracing of the EKF code might prove that they are equivalent...

**Comment by Williangalvani** [comment]
> "4" is type; the value is 1. (That's how QGC dumps parameters.)

lol I misread that badly, sorry. I'll try to test this asap, thanks!

**Review by Williangalvani — APPROVED** [review]
tested and works as expected. user feedback would be nice, but I think the feature is worth merging asap.

Thanks Clyde!

**Pull request merged**
